// <auto-generated />
using System;
using Dwapi.Mnch.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dwapi.Mnch.Infrastructure.Migrations
{
    [DbContext(typeof(MnchContext))]
    [Migration("20220620205817_MnchUpdateColumnTypes")]
    partial class MnchUpdateColumnTypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.AncVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ANCClinicNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ANCVisitNo")
                        .HasColumnType("int");

                    b.Property<string>("AZTBabyDispense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AntenatalExercises")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BP")
                        .HasColumnType("int");

                    b.Property<string>("BreastExam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CACxScreen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CACxScreenMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChronicIllness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CounselledOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Deworming")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiabetesTest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FGM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FGMComplications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GestationWeeks")
                        .HasColumnType("int");

                    b.Property<string>("HIVStatusBeforeANC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVTest1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVTest1Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVTest2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVTest2Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVTestFinalResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVTestType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVTestingDone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Haemoglobin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IronSupplementsGiven")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MUAC")
                        .HasColumnType("int");

                    b.Property<string>("MalariaProphylaxis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MotherGivenHAART")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotherProphylaxisGiven")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NVPBabyDispense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextAppointmentANC")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("OxygenSaturation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PartnerHIVStatusANC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerHIVTestingANC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientMnchID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PostParturmFP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreventiveServices")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Processed")
                        .HasColumnType("bit");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PulseRate")
                        .HasColumnType("int");

                    b.Property<string>("QueueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceivedMosquitoNet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferralReasons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferredFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferredTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RespiratoryRate")
                        .HasColumnType("int");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SyphilisTestDone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyphilisTestResults")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyphilisTestType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyphilisTreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyphilisTreatment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TBScreening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Temp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TetanusDose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrinalysisVariables")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VLDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VLResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VLSampleTaken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VisitID")
                        .HasColumnType("int");

                    b.Property<int?>("WHOStaging")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("AncVisits");
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Items")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId");

                    b.ToTable("Cargoes");
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.CwcEnrolment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ARTMother")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARTRegimenMother")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ARTStartDateMother")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("BirthLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BirthOrder")
                        .HasColumnType("int");

                    b.Property<string>("BirthType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthWeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BreastFeeding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Gestation")
                        .HasColumnType("datetime2");

                    b.Property<string>("HEI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HEIDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HEIID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModeOfDelivery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherAlive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MothersCCCNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MothersPkv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NVP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientIDCWC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("Pkv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfDelivery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Processed")
                        .HasColumnType("bit");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferredFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegistrationAtCWC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RegistrationAtHEI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("SpecialCare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialNeeds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransferIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferInDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferredFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VisitID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("CwcEnrolments");
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.CwcVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("DangerSigns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dewormed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Disability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FollowUP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Immunization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InfantFeeding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MNPsSupplementation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MUAC")
                        .HasColumnType("int");

                    b.Property<string>("MedicationGiven")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Milestones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextAppointment")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("OxygenSaturation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PatientMnchID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<bool?>("Processed")
                        .HasColumnType("bit");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PulseRate")
                        .HasColumnType("int");

                    b.Property<string>("QueueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceivedMosquitoNet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferralReasons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferredFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferredTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RespiratoryRate")
                        .HasColumnType("int");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stunted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TBAssessment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Temp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VisitID")
                        .HasColumnType("int");

                    b.Property<string>("VitaminA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WeightCategory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("CwcVisits");
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.Docket", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Instance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Dockets");
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MasterFacilityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(120)")
                        .HasMaxLength(120);

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SnapshotDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SnapshotSiteCode")
                        .HasColumnType("int");

                    b.Property<int?>("SnapshotVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MasterFacilityId");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.Hei", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BasellineVL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BasellineVLDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmatoryPCR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConfirmatoryPCRDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("DNAPCR1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DNAPCR1Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DNAPCR2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DNAPCR2Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DNAPCR3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DNAPCR3Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinalyAntibody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinalyAntibodyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HEIExitCritearia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HEIExitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HEIHIVStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientMnchID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<bool?>("Processed")
                        .HasColumnType("bit");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("Heis");
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.Manifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateArrived")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLogged")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EmrId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmrName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmrSetup")
                        .HasColumnType("int");

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Recieved")
                        .HasColumnType("int");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sent")
                        .HasColumnType("int");

                    b.Property<Guid?>("Session")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("Manifests");
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.MasterFacility", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(120)")
                        .HasMaxLength(120);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(120)")
                        .HasMaxLength(120);

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SnapshotDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SnapshotSiteCode")
                        .HasColumnType("int");

                    b.Property<int?>("SnapshotVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MasterFacilities");
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.MatVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ANCVisits")
                        .HasColumnType("int");

                    b.Property<string>("AdmissionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ApgarScore1")
                        .HasColumnType("int");

                    b.Property<int?>("ApgarScore10")
                        .HasColumnType("int");

                    b.Property<int?>("ApgarScore5")
                        .HasColumnType("int");

                    b.Property<int?>("BabyBirthNumber")
                        .HasColumnType("int");

                    b.Property<string>("BabyGivenProphylaxis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthWeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthWithDeformity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BloodLoss")
                        .HasColumnType("int");

                    b.Property<string>("BloodLossVisual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChlorhexidineApplied")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditonAfterDelivery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CounselledOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfDelivery")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryComplications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurationOfDelivery")
                        .HasColumnType("int");

                    b.Property<string>("Emr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GestationAtBirth")
                        .HasColumnType("int");

                    b.Property<string>("HIV1Results")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIV2Results")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVStatusLastANC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVTest1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVTest2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVTestFinalResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVTestingDone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InitiatedBF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KangarooCare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MaternalDeath")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModeOfDelivery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherDischargeDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherGivenCTX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NoBabiesDelivered")
                        .HasColumnType("int");

                    b.Property<string>("OnARTANC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerHIVStatusMAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerHIVTestingMAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientMnchID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PlacentaComplete")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Processed")
                        .HasColumnType("bit");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferredFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferredTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexBaby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusBabyDischarge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SyphilisTestResults")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TetracyclineGiven")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UterotonicGiven")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaginalExamination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VisitID")
                        .HasColumnType("int");

                    b.Property<string>("VitaminKGiven")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("MatVisits");
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.MnchArt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastARTDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastRegimen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastRegimenLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientHeiID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientMnchID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("Pkv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Processed")
                        .HasColumnType("bit");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RegistrationAtCCC")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartARTDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartRegimen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartRegimenLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusAtCCC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("MnchArts");
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.MnchEnrolment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EDDFromLMP")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EnrollmentDateAtMnch")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FirstVisitAnc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gravidae")
                        .HasColumnType("int");

                    b.Property<string>("HIVStatusBeforeANC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HIVTestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LMP")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MnchNumber")
                        .HasColumnType("datetime2");

                    b.Property<string>("Parity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerHIVStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PartnerHIVTestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientMnchID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<bool?>("Processed")
                        .HasColumnType("bit");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ServiceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusAtMnch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("MnchEnrolments");
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.MnchLab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OrderedbyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientMNCH_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<bool?>("Processed")
                        .HasColumnType("bit");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReportedbyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SatelliteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TestName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VisitID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("MnchLabs");
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.MotherBabyPair", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BabyPatientMncHeiID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BabyPatientPK")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotherPatientMncHeiID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MotherPatientPK")
                        .HasColumnType("int");

                    b.Property<string>("PatientIDCCC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<bool?>("Processed")
                        .HasColumnType("bit");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("MotherBabyPairs");
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.PatientMnch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FirstEnrollmentAtMnch")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InSchool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientHeiID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientMnchID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PatientResidentCounty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientResidentSubCounty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientResidentWard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pkv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Processed")
                        .HasColumnType("bit");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("MnchPatients");
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.PncVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BP")
                        .HasColumnType("int");

                    b.Property<string>("BabyConditon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BabyFeeding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Breast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BreastExam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CACxScreenMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CACxScreenResults")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CSScar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientScreenedCACx")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CounselledOnFP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoupleCounselled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExtracted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Last_Modified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Episiotomy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Fistula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVTest1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVTest1Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVTest2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVTest2Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVTestFinalResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIVTestingDone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HaematinicsGiven")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasPallor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Immunization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InfantFeeding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InfantProphylaxisGiven")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lochia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MUAC")
                        .HasColumnType("int");

                    b.Property<string>("MaternalComplications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModeOfDelivery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherProphylaxisGiven")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextAppointmentPNC")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("OxygenSaturation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PNCRegisterNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PNCVisitNo")
                        .HasColumnType("int");

                    b.Property<string>("PPH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pallor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerHIVResultPNC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerHIVTestingPNC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientMnchID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPk")
                        .HasColumnType("int");

                    b.Property<string>("PlaceOfDelivery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreventiveServices")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriorHIVStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Processed")
                        .HasColumnType("bit");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PulseRate")
                        .HasColumnType("int");

                    b.Property<string>("QueueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceivedFP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferredFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferredTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RespiratoryRate")
                        .HasColumnType("int");

                    b.Property<int>("SiteCode")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TBScreening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Temp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UmbilicalCord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UterusInvolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VisitID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("PncVisits");
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocketId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DocketId");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.AncVisit", b =>
                {
                    b.HasOne("Dwapi.Mnch.Core.Domain.Facility", null)
                        .WithMany("AncVisits")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.Cargo", b =>
                {
                    b.HasOne("Dwapi.Mnch.Core.Domain.Manifest", null)
                        .WithMany("Cargoes")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.CwcEnrolment", b =>
                {
                    b.HasOne("Dwapi.Mnch.Core.Domain.Facility", null)
                        .WithMany("CwcEnrolments")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.CwcVisit", b =>
                {
                    b.HasOne("Dwapi.Mnch.Core.Domain.Facility", null)
                        .WithMany("CwcVisits")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.Facility", b =>
                {
                    b.HasOne("Dwapi.Mnch.Core.Domain.MasterFacility", null)
                        .WithMany("Mentions")
                        .HasForeignKey("MasterFacilityId");
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.Hei", b =>
                {
                    b.HasOne("Dwapi.Mnch.Core.Domain.Facility", null)
                        .WithMany("Heis")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.Manifest", b =>
                {
                    b.HasOne("Dwapi.Mnch.Core.Domain.Facility", null)
                        .WithMany("Manifests")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.MatVisit", b =>
                {
                    b.HasOne("Dwapi.Mnch.Core.Domain.Facility", null)
                        .WithMany("MatVisits")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.MnchArt", b =>
                {
                    b.HasOne("Dwapi.Mnch.Core.Domain.Facility", null)
                        .WithMany("MnchArts")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.MnchEnrolment", b =>
                {
                    b.HasOne("Dwapi.Mnch.Core.Domain.Facility", null)
                        .WithMany("MnchEnrolments")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.MnchLab", b =>
                {
                    b.HasOne("Dwapi.Mnch.Core.Domain.Facility", null)
                        .WithMany("MnchLabs")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.MotherBabyPair", b =>
                {
                    b.HasOne("Dwapi.Mnch.Core.Domain.Facility", null)
                        .WithMany("MotherBabyPairs")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.PatientMnch", b =>
                {
                    b.HasOne("Dwapi.Mnch.Core.Domain.Facility", null)
                        .WithMany("MnchPatients")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.PncVisit", b =>
                {
                    b.HasOne("Dwapi.Mnch.Core.Domain.Facility", null)
                        .WithMany("PncVisits")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwapi.Mnch.Core.Domain.Subscriber", b =>
                {
                    b.HasOne("Dwapi.Mnch.Core.Domain.Docket", null)
                        .WithMany("Subscribers")
                        .HasForeignKey("DocketId");
                });
#pragma warning restore 612, 618
        }
    }
}
